/* ============================================================
   Ad Fontes Project — Catecismos reformados
   Preguntas y respuestas. Textos de dominio público, en español.
   Las referencias entre corchetes se convierten en enlaces a la Biblia.
   ============================================================ */

const CATECISMOS = {

  baptista1693: {
    titulo: 'Catecismo Bautista (1693)',
    sub: 'Bautista · 1693',
    nota: 'También llamado Catecismo de Keach. Compuesto por los bautistas particulares (Benjamin Keach y William Collins) siguiendo de cerca el Catecismo Menor de Westminster, con los distintivos bautistas sobre el bautismo de creyentes y la Cena del Señor. Sigue a la Confesión de 1689.',
    fuente: 'Catecismo Bautista de 1693 · texto de dominio público. Toca una referencia para leerla en la Biblia.',
    preguntas: [
      { p: '¿Quién es el primer y principal Ser?', r: 'Dios es el primer y principal Ser.', refs: ['Is 44:6','Sal 97:9'] },
      { p: '¿Debe todo hombre creer que hay Dios?', r: 'Todo hombre debe creer que hay Dios, y es su gran pecado y locura no creerlo.', refs: ['He 11:6','Sal 14:1'] },
      { p: '¿Cómo podemos saber que hay Dios?', r: 'La luz de la naturaleza en el hombre y las obras de Dios declaran claramente que hay Dios; pero solo su Palabra y su Espíritu lo revelan de manera plena y eficaz para la salvación de los pecadores.', refs: ['Sal 19:1-3','Ro 1:19-20','2 Ti 3:15','1 Co 2:10'] },
      { p: '¿Qué es la Palabra de Dios?', r: 'Las Santas Escrituras del Antiguo y Nuevo Testamento son la Palabra de Dios, y la única regla segura de fe y obediencia.', refs: ['2 Ti 3:16','Ef 2:20'] },
      { p: '¿Pueden todos los hombres usar las Santas Escrituras?', r: 'Todos los hombres no solo tienen permiso, sino mandato y exhortación de leer, oír y entender las Santas Escrituras.', refs: ['Jn 5:39','Lc 16:29','Hch 17:11'] },
      { p: '¿Qué enseñan principalmente las Escrituras?', r: 'Las Escrituras enseñan principalmente lo que el hombre ha de creer acerca de Dios, y qué deber Dios requiere del hombre.', refs: ['2 Ti 1:13','2 Ti 3:16'] },
      { p: '¿Qué es Dios?', r: 'Dios es Espíritu, infinito, eterno e inmutable en su ser, sabiduría, poder, santidad, justicia, bondad y verdad.', refs: ['Jn 4:24','Job 11:7-9','Sal 90:2','Stg 1:17','Éx 34:6-7'] },
      { p: '¿Hay más de un Dios?', r: 'Hay un solo Dios, el vivo y verdadero.', refs: ['Dt 6:4','Jer 10:10'] },
      { p: '¿Cuántas personas hay en la Deidad?', r: 'Hay tres personas en la Deidad: el Padre, el Hijo y el Espíritu Santo; y estas tres son un solo Dios, de una misma sustancia, iguales en poder y gloria.', refs: ['1 Jn 5:7','Mt 28:19'] },
      { p: '¿Cuáles son los decretos de Dios?', r: 'Los decretos de Dios son su propósito eterno, según el consejo de su voluntad, por el cual, para su propia gloria, ha preordenado todo cuanto sucede.', refs: ['Ef 1:11','Ro 11:36','Dn 4:35'] },
      { p: '¿Cómo ejecuta Dios sus decretos?', r: 'Dios ejecuta sus decretos en las obras de la creación y de la providencia.', refs: ['Ap 4:11','Dn 4:35'] },
      { p: '¿Qué es la obra de la creación?', r: 'La obra de la creación es aquella por la cual Dios hizo todas las cosas de la nada, por la palabra de su poder, en el espacio de seis días, y todo muy bueno.', refs: ['Gn 1:1','He 11:3','Éx 20:11','Gn 1:31'] },
      { p: '¿Cómo creó Dios al hombre?', r: 'Dios creó al hombre, varón y mujer, a su propia imagen, en conocimiento, justicia y santidad, con dominio sobre las criaturas.', refs: ['Gn 1:26-28','Col 3:10','Ef 4:24'] },
      { p: '¿Cuáles son las obras de la providencia de Dios?', r: 'Las obras de la providencia de Dios son su santísima, sapientísima y poderosísima preservación y gobierno de todas sus criaturas y de todas sus acciones.', refs: ['Sal 145:17','Sal 103:19','Mt 10:29-31','He 1:3'] },
      { p: '¿Qué acto especial de providencia ejerció Dios hacia el hombre en el estado en que fue creado?', r: 'Cuando Dios creó al hombre, hizo con él un pacto de vida bajo la condición de una obediencia perfecta, prohibiéndole comer del árbol del conocimiento del bien y del mal, bajo pena de muerte.', refs: ['Gá 3:12','Gn 2:17'] },
      { p: '¿Permanecieron nuestros primeros padres en el estado en que fueron creados?', r: 'Nuestros primeros padres, dejados a la libertad de su propia voluntad, cayeron del estado en que fueron creados, pecando contra Dios al comer del fruto prohibido.', refs: ['Ec 7:29','Gn 3:6-8'] },
      { p: '¿Qué es el pecado?', r: 'El pecado es toda falta de conformidad con la ley de Dios, o toda transgresión de ella.', refs: ['1 Jn 3:4'] },
      { p: '¿A qué estado llevó la caída a la humanidad?', r: 'La caída llevó a la humanidad a un estado de pecado y de miseria.', refs: ['Ro 5:12'] },
      { p: '¿En qué consiste la pecaminosidad de aquel estado en que cayó el hombre?', r: 'La pecaminosidad de aquel estado consiste en la culpa del primer pecado de Adán, la falta de justicia original y la corrupción de toda su naturaleza, que comúnmente se llama pecado original, junto con todas las transgresiones que de él proceden.', refs: ['Ro 5:12','Ro 5:19','Ef 2:1-3','Stg 1:14-15','Mt 15:19'] },
      { p: '¿Cuál es la miseria de aquel estado en que cayó el hombre?', r: 'Toda la humanidad, por su caída, perdió la comunión con Dios, quedó bajo su ira y maldición, y así hecha sujeta a todas las miserias de esta vida, a la muerte misma, y a las penas del infierno para siempre.', refs: ['Gn 3:8,24','Ef 2:3','Gá 3:10','Lm 3:39','Ro 6:23','Mt 25:41'] },
      { p: '¿Dejó Dios que toda la humanidad pereciera en el estado de pecado y miseria?', r: 'Dios, por su mero beneplácito, desde toda la eternidad, habiendo escogido a algunos para vida eterna, entró en un pacto de gracia para librarlos del estado de pecado y miseria, y traerlos a un estado de salvación por un Redentor.', refs: ['Ef 1:3-4','2 Ts 2:13-14','Ro 5:21'] },
      { p: '¿Quién es el Redentor de los elegidos de Dios?', r: 'El único Redentor de los elegidos de Dios es el Señor Jesucristo, quien, siendo el eterno Hijo de Dios, se hizo hombre, y así fue y sigue siendo Dios y hombre, en dos naturalezas distintas y una sola persona, para siempre.', refs: ['1 Ti 2:5-6','Jn 1:14','Gá 4:4','Lc 1:35','Col 2:9','He 7:24-25'] },
      { p: '¿Cómo llegó Cristo, siendo el Hijo de Dios, a ser hombre?', r: 'Cristo, el Hijo de Dios, se hizo hombre tomando para sí un cuerpo verdadero y un alma racional, siendo concebido por el poder del Espíritu Santo en el vientre de la virgen María, y nacido de ella, mas sin pecado.', refs: ['Jn 1:14','He 2:14,16-17','Lc 1:27,31,35','He 4:15'] },
      { p: '¿Qué oficios cumple Cristo como nuestro Redentor?', r: 'Cristo, como nuestro Redentor, cumple los oficios de profeta, de sacerdote y de rey, tanto en su estado de humillación como en el de exaltación.', refs: ['Hch 3:22','He 5:5-6','Sal 2:6'] },
      { p: '¿Cómo cumple Cristo el oficio de profeta?', r: 'Cristo cumple el oficio de profeta al revelarnos, por su Palabra y su Espíritu, la voluntad de Dios para nuestra salvación.', refs: ['Jn 1:18','1 P 1:10-12','Jn 15:15','Jn 20:31'] },
      { p: '¿Cómo cumple Cristo el oficio de sacerdote?', r: 'Cristo cumple el oficio de sacerdote al ofrecerse a sí mismo una sola vez en sacrificio para satisfacer la justicia divina y reconciliarnos con Dios, y al interceder continuamente por nosotros.', refs: ['He 9:14,28','He 2:17','He 7:24-25'] },
      { p: '¿Cómo cumple Cristo el oficio de rey?', r: 'Cristo cumple el oficio de rey al sujetarnos a sí mismo, gobernarnos y defendernos, y refrenar y vencer a todos sus enemigos y los nuestros.', refs: ['Sal 110:3','1 Co 15:25','Col 1:13'] },
      { p: '¿En qué consistió la humillación de Cristo?', r: 'La humillación de Cristo consistió en haber nacido, y eso en baja condición; en ser hecho bajo la ley; en padecer las miserias de esta vida, la ira de Dios y la muerte maldita de la cruz; en ser sepultado y permanecer bajo el poder de la muerte por un tiempo.', refs: ['Lc 2:7','Gá 4:4','Is 53:2-3','Lc 22:44','Fil 2:8','1 Co 15:3-4'] },
      { p: '¿En qué consiste la exaltación de Cristo?', r: 'La exaltación de Cristo consiste en su resurrección de entre los muertos al tercer día, su ascensión al cielo, su sesión a la diestra de Dios Padre, y su venida para juzgar al mundo en el día postrero.', refs: ['1 Co 15:4','Mr 16:19','Ef 1:20','Hch 1:11','Hch 17:31'] },
      { p: '¿Cómo somos hechos partícipes de la redención comprada por Cristo?', r: 'Somos hechos partícipes de la redención comprada por Cristo por la aplicación eficaz de ella a nosotros, por su Santo Espíritu.', refs: ['Jn 1:12','Tit 3:5-6','Jn 3:5-6'] },
      { p: '¿Cómo aplica el Espíritu la redención comprada por Cristo?', r: 'El Espíritu aplica la redención comprada por Cristo obrando en nosotros la fe, y uniéndonos así a Cristo en nuestro llamamiento eficaz.', refs: ['Ef 2:8','Ef 3:17','1 Co 1:9'] },
      { p: '¿Qué es el llamamiento eficaz?', r: 'El llamamiento eficaz es la obra del Espíritu de Dios, por la cual, convenciéndonos de nuestro pecado y miseria, iluminando nuestras mentes en el conocimiento de Cristo, y renovando nuestra voluntad, nos persuade y capacita para abrazar a Jesucristo, ofrecido gratuitamente a nosotros en el evangelio.', refs: ['2 Ti 1:9','2 Ts 2:13-14','Hch 26:18','Ez 36:26-27','Jn 6:44-45','Fil 2:13'] },
      { p: '¿De qué beneficios participan en esta vida los que son llamados eficazmente?', r: 'Los que son llamados eficazmente participan en esta vida de la justificación, la adopción, la santificación, y los diversos beneficios que en esta vida las acompañan o de ellas proceden.', refs: ['Ro 8:30','Ef 1:5','1 Co 6:11','Ro 5:1-2,5'] },
      { p: '¿Qué es la justificación?', r: 'La justificación es un acto de la gracia gratuita de Dios, por el cual perdona todos nuestros pecados y nos acepta como justos ante sus ojos, solo por causa de la justicia de Cristo imputada a nosotros, y recibida solo por la fe.', refs: ['Ro 3:24','Ef 1:7','2 Co 5:19,21','Ro 5:19','Gá 2:16','Fil 3:9'] },
      { p: '¿Qué es la adopción?', r: 'La adopción es un acto de la gracia gratuita de Dios, por el cual somos recibidos en el número de los hijos de Dios y tenemos derecho a todos sus privilegios.', refs: ['1 Jn 3:1','Jn 1:12','Ro 8:17'] },
      { p: '¿Qué es la santificación?', r: 'La santificación es la obra de la gracia gratuita de Dios, por la cual somos renovados en todo nuestro ser a imagen de Dios, y capacitados cada vez más para morir al pecado y vivir para la justicia.', refs: ['2 Ts 2:13','Ef 4:23-24','Ro 6:4,6','Ro 8:1'] },
      { p: '¿Qué beneficios acompañan o proceden en esta vida de la justificación, la adopción y la santificación?', r: 'Los beneficios que en esta vida acompañan o proceden de la justificación, la adopción y la santificación son: la seguridad del amor de Dios, la paz de conciencia, el gozo en el Espíritu Santo, el crecimiento en gracia, y la perseverancia en ella hasta el fin.', refs: ['Ro 5:1-2,5','Ro 14:17','Pr 4:18','1 Jn 5:13','1 P 1:5'] },
      { p: '¿Qué beneficios reciben los creyentes de Cristo en la muerte?', r: 'Las almas de los creyentes son, en su muerte, hechas perfectas en santidad, y pasan inmediatamente a la gloria; y sus cuerpos, unidos todavía a Cristo, descansan en sus sepulcros hasta la resurrección.', refs: ['He 12:23','Fil 1:23','2 Co 5:8','1 Ts 4:14','Is 57:2','Job 19:26'] },
      { p: '¿Qué beneficios reciben los creyentes de Cristo en la resurrección?', r: 'En la resurrección, los creyentes, siendo resucitados en gloria, serán reconocidos y absueltos abiertamente en el día del juicio, y hechos perfectamente bienaventurados, en el pleno gozo de Dios, por toda la eternidad.', refs: ['1 Co 15:43','Mt 25:23','1 Jn 3:2','1 Ts 4:17'] },
      { p: '¿Qué será de los malvados en su muerte?', r: 'Las almas de los malvados serán, en su muerte, arrojadas a los tormentos del infierno, y sus cuerpos yacerán en sus sepulcros hasta la resurrección y el juicio del gran día.', refs: ['Lc 16:22-24','Sal 49:14','Jn 5:28-29'] }
    ]
  }

};
