/* ============================================================
   Ad Fontes Project — Historia de la Iglesia
   Artículos narrativos. Más relatos por venir.
   Bloques: {t:'p'|'h'|'sub'|'cita'|'nota', x, autor, p, refs}
   ============================================================ */

const HISTORIA = {

  worms: {
    titulo: 'La Dieta de Worms',
    sub: 'Historia de la Iglesia · 1521',
    icono: '⚖️',
    resumen: 'Lutero ante el emperador: «aquí estoy; no puedo hacer otra cosa».',
    ficha: [
      { k: 'Fecha', v: 'Enero–mayo de 1521' },
      { k: 'Lugar', v: 'Worms, Sacro Imperio Romano Germánico' },
      { k: 'Protagonista', v: 'Martín Lutero ante el emperador Carlos V' },
      { k: 'Resultado', v: 'Edicto de Worms: Lutero declarado hereje y proscrito' }
    ],
    fuente: 'Relato histórico. Las referencias entre paréntesis remiten a la Escritura; tócalas para leerlas.',
    cuerpo: [
      { t: 'p', x: 'En abril de 1521, un monje agustino compareció ante el emperador Carlos V y los príncipes del Sacro Imperio Romano Germánico. La «dieta» (en alemán, <em>Reichstag</em>) era la asamblea imperial —una especie de parlamento—; y aquella, reunida en la ciudad alemana de Worms, se convirtió en una de las grandes bisagras de la historia de la Iglesia.' },
      { t: 'h', x: 'El camino hasta Worms' },
      { t: 'p', x: 'Lutero había publicado sus 95 tesis en 1517 y, en los años siguientes, escribió tratados que cuestionaban de raíz doctrinas y prácticas de la Iglesia de Roma. Sus libros corrían por toda Europa gracias a la imprenta. Roma terminó excomulgándolo, y el Imperio lo citó a comparecer para dar cuenta de sus escritos.' },
      { t: 'h', x: '«¿Te retractas?»' },
      { t: 'p', x: 'En Worms se le exigieron dos cosas: reconocer que los libros amontonados sobre la mesa eran suyos, y retractarse de su contenido. Lo primero lo admitió sin dudar. Para lo segundo pidió un día de plazo, y se retiró a orar.' },
      { t: 'h', x: 'La respuesta que cambió la historia' },
      { t: 'p', x: 'Al día siguiente, negándose a retractarse a menos que lo convencieran por el testimonio de la Escritura o por la razón evidente —pues, dijo, ni los papas ni los concilios son de fiar, ya que se han contradicho unos a otros—, pronunció las palabras que la memoria protestante ha guardado:' },
      { t: 'cita', x: 'Mi conciencia está cautiva de la Palabra de Dios. No puedo ni quiero retractarme de nada, pues obrar contra la conciencia no es seguro ni honesto. Aquí estoy; no puedo hacer otra cosa. Que Dios me ayude. Amén.', autor: 'Martín Lutero · Worms, 1521' },
      { t: 'nota', x: 'Los historiadores discuten si pronunció exactamente la frase «Aquí estoy» (Hier stehe ich); pero el sentido de su declaración —una conciencia atada a la Escritura— está bien atestiguado.' },
      { t: 'h', x: 'El Edicto de Worms' },
      { t: 'p', x: 'El emperador lo declaró hereje y proscrito: sus escritos fueron prohibidos y cualquiera podía apresarlo sin castigo. Pero Federico el Sabio, príncipe de Sajonia, organizó un «secuestro» protector y lo escondió en el castillo de Wartburg. Allí, lejos del peligro, Lutero tradujo el Nuevo Testamento al alemán, poniendo la Palabra de Dios en la lengua del pueblo.' },
      { t: 'h', x: 'Por qué importa a la fe reformada' },
      { t: 'sub', x: 'Sola Scriptura', p: 'La autoridad final es la Escritura, por encima de concilios y tradiciones humanas.', refs: ['2 Ti 3:16-17','Hch 17:11','Is 8:20'] },
      { t: 'sub', x: 'La conciencia cautiva de la Palabra', p: 'La conciencia del creyente se somete a Dios y a su Palabra, y no a autoridades humanas cuando estas contradicen la Escritura.', refs: ['Hch 5:29','Ro 14:23','Stg 4:12'] },
      { t: 'sub', x: 'El inicio visible de la Reforma', p: 'Aunque la Reforma ya había comenzado, en Worms el conflicto se hizo público, imperial e irreversible.', refs: [] },
      { t: 'h', x: 'La bisagra' },
      { t: 'p', x: 'Imagina el salón imperial a la luz de las antorchas. De un lado, el emperador, los príncipes, los obispos y los juristas; del otro, un monje solo, con una mesa cargada de libros. La verdadera pregunta no era «¿te retractas?», sino: ¿qué tiene la última palabra, la autoridad de la Iglesia o la Palabra de Dios?' },
      { t: 'p', x: 'Lutero no salió de Worms con poder político; salió con algo que él tenía por más fuerte: una conciencia atada a la Escritura. Por eso, para tantos protestantes, Worms es una bisagra de la historia: la puerta de la Reforma ya no pudo volver a cerrarse.' }
    ],
    tesis: {
      titulo: 'Las 95 tesis',
      sub: 'Wittenberg · 31 de octubre de 1517',
      intro: 'Cuatro años antes de Worms, Lutero clavó en la puerta de la iglesia del castillo de Wittenberg una <em>Disputa sobre el poder de las indulgencias</em>: noventa y cinco proposiciones para el debate académico. No pretendían romper con Roma, sino corregir un abuso; pero encendieron la mecha de la Reforma. Aquí está el texto completo.',
      fuente: 'Traducción del latín («Disputatio pro declaratione virtutis indulgentiarum», 1517). Documento de dominio público.',
      items: [
        'Al decir nuestro Señor y Maestro Jesucristo «Haced penitencia…», quiso que toda la vida de los creyentes fuera penitencia.',
        'Esta palabra no puede entenderse de la penitencia sacramental, es decir, de la confesión y satisfacción que se celebra por el ministerio de los sacerdotes.',
        'Sin embargo, no se refiere solamente a la penitencia interior; más aún, la penitencia interior es nula si no obra exteriormente diversas mortificaciones de la carne.',
        'Por tanto, la pena permanece mientras permanece el aborrecimiento de sí mismo (esto es, la verdadera penitencia interior), es decir, hasta la entrada en el reino de los cielos.',
        'El Papa no quiere ni puede remitir ninguna pena, salvo aquellas que ha impuesto por su propia autoridad o por la de los cánones.',
        'El Papa no puede remitir culpa alguna sino declarando y aprobando que ha sido remitida por Dios; o, ciertamente, remitiéndola en los casos reservados a él; despreciados los cuales, la culpa permanecería intacta.',
        'Dios a nadie perdona la culpa sin someterlo al mismo tiempo, humillado en todo, al sacerdote su vicario.',
        'Los cánones penitenciales se imponen solo a los vivos, y, según los mismos, nada debe imponerse a los moribundos.',
        'Por lo cual nos beneficia el Espíritu Santo en el Papa, al exceptuar siempre en sus decretos el artículo de la muerte y de la necesidad.',
        'Obran mal e ignorantemente los sacerdotes que a los moribundos les reservan penitencias canónicas para el purgatorio.',
        'Aquella cizaña de cambiar la pena canónica en pena del purgatorio parece haber sido sembrada mientras los obispos dormían.',
        'Antiguamente las penas canónicas se imponían no después, sino antes de la absolución, como pruebas de la verdadera contrición.',
        'Los moribundos con la muerte pagan todo, y ya están muertos para las leyes canónicas, teniendo por derecho la exención de ellas.',
        'La salud o el amor imperfecto del moribundo trae necesariamente consigo gran temor, y tanto mayor cuanto menor sea aquel.',
        'Este temor y horror basta por sí solo (por callar lo demás) para constituir la pena del purgatorio, pues está muy cerca del horror de la desesperación.',
        'Parece que infierno, purgatorio y cielo difieren como difieren desesperación, casi desesperación y seguridad.',
        'Parece necesario que a las almas en el purgatorio, así como les disminuye el horror, así les aumente el amor.',
        'Ni parece probado, ni por razones ni por Escrituras, que estén fuera del estado de mérito o de aumento del amor.',
        'Ni parece probado que estén seguras y ciertas de su bienaventuranza, al menos todas, aunque nosotros estemos muy seguros de ello.',
        'Por tanto, el Papa, al decir «plena remisión de todas las penas», no entiende simplemente de todas, sino solo de las impuestas por él mismo.',
        'Yerran, pues, los predicadores de indulgencias que dicen que por las indulgencias del Papa el hombre queda libre y salvo de toda pena.',
        'Antes bien, ninguna pena remite a las almas en el purgatorio que en esta vida debieron pagar según los cánones.',
        'Si a alguno puede concederse alguna remisión de todas las penas, es cierto que solo se concede a los más perfectos, es decir, a poquísimos.',
        'Por lo cual es forzoso que la mayor parte del pueblo sea engañada por aquella indiferente y pomposa promesa de la pena.',
        'El poder que el Papa tiene en general sobre el purgatorio, tal lo tiene cualquier obispo y cura en particular en su diócesis y parroquia.',
        'Muy bien hace el Papa en dar remisión a las almas, no por el poder de las llaves (que no tiene), sino por vía de sufragio.',
        'Predican cosa humana quienes dicen que, tan pronto como suena la moneda echada en la caja, el alma sale volando.',
        'Cierto es que, al sonar la moneda en la caja, pueden crecer la ganancia y la avaricia; pero el sufragio de la Iglesia está solo en la voluntad de Dios.',
        '¿Quién sabe si todas las almas del purgatorio quieren ser rescatadas, como se cuenta que sucedió con san Severino y san Pascual?',
        'Nadie está seguro de la verdad de su contrición, y mucho menos de haber conseguido la plena remisión.',
        'Tan raro es quien verdaderamente se arrepiente como quien verdaderamente compra indulgencias, es decir, rarísimo.',
        'Serán condenados eternamente, junto con sus maestros, quienes se creen seguros de su salvación por cartas de indulgencia.',
        'Hay que guardarse mucho de quienes dicen que aquellas indulgencias del Papa son el don inestimable de Dios por el cual el hombre se reconcilia con Dios.',
        'Porque aquellas gracias de indulgencia solo miran a las penas de la satisfacción sacramental, establecidas por los hombres.',
        'No predican cristianamente quienes enseñan que no es necesaria la contrición para los que quieren redimir las almas o comprar confesionales.',
        'Cualquier cristiano verdaderamente contrito tiene plena remisión de la pena y de la culpa, aun sin cartas de indulgencia.',
        'Cualquier verdadero cristiano, vivo o muerto, tiene participación en todos los bienes de Cristo y de la Iglesia, dada por Dios, aun sin cartas de indulgencia.',
        'Sin embargo, no debe despreciarse la remisión y participación otorgada por el Papa, pues es declaración de la remisión divina.',
        'Es dificilísimo, aun para los más doctos teólogos, ensalzar a la vez ante el pueblo la abundancia de las indulgencias y la verdad de la contrición.',
        'La verdadera contrición busca y ama las penas; la abundancia de las indulgencias afloja y hace aborrecerlas, al menos da ocasión para ello.',
        'Con cautela deben predicarse las indulgencias apostólicas, no sea que el pueblo entienda falsamente que son preferibles a las demás buenas obras de caridad.',
        'Debe enseñarse a los cristianos que la mente del Papa no es que la compra de indulgencias se compare en modo alguno con las obras de misericordia.',
        'Debe enseñarse a los cristianos que quien da al pobre o presta al necesitado obra mejor que si comprara indulgencias.',
        'Porque por la obra de caridad crece la caridad y el hombre se hace mejor; pero por las indulgencias no se hace mejor, sino solo más libre de la pena.',
        'Debe enseñarse a los cristianos que quien, viendo a un necesitado y pasándolo por alto, da su dinero para indulgencias, no compra las indulgencias del Papa, sino la indignación de Dios.',
        'Debe enseñarse a los cristianos que, si no les sobra, están obligados a retener lo necesario para su casa, y de ningún modo malgastarlo en indulgencias.',
        'Debe enseñarse a los cristianos que la compra de indulgencias es libre, no mandada.',
        'Debe enseñarse a los cristianos que el Papa, al conceder indulgencias, tiene más necesidad y desea más una oración devota por él que dinero pronto.',
        'Debe enseñarse a los cristianos que las indulgencias del Papa son útiles si no ponen en ellas su confianza, pero muy dañosas si por ellas pierden el temor de Dios.',
        'Debe enseñarse a los cristianos que, si el Papa conociera las exacciones de los predicadores de indulgencias, preferiría que la basílica de san Pedro fuese reducida a cenizas antes que edificada con la piel, carne y huesos de sus ovejas.',
        'Debe enseñarse a los cristianos que el Papa estaría dispuesto, como es su deber, a dar de su propio dinero a muchos de aquellos a quienes ciertos predicadores sacan el dinero, aunque hubiera de vender la basílica de san Pedro.',
        'Vana es la confianza de salvarse por cartas de indulgencia, aunque el comisario, o aun el mismo Papa, empeñara su alma por ellas.',
        'Son enemigos de Cristo y del Papa quienes, por predicar las indulgencias, mandan callar del todo la Palabra de Dios en las demás iglesias.',
        'Se hace injuria a la Palabra de Dios cuando en un mismo sermón se emplea igual o más tiempo en las indulgencias que en ella.',
        'La mente del Papa es que, si las indulgencias (que es lo mínimo) se celebran con una campana, una pompa y una ceremonia, el Evangelio (que es lo máximo) debe predicarse con cien campanas, cien pompas y cien ceremonias.',
        'Los tesoros de la Iglesia, de donde el Papa saca las indulgencias, ni están suficientemente nombrados ni conocidos entre el pueblo de Cristo.',
        'Que no sean temporales es evidente, pues muchos predicadores no los reparten con facilidad, sino que solo los recogen.',
        'Ni tampoco son los méritos de Cristo y de los santos, porque estos, aun sin el Papa, obran siempre la gracia del hombre interior y la cruz, la muerte y el infierno del exterior.',
        'San Lorenzo dijo que los pobres eran los tesoros de la Iglesia, pero usó el vocablo según el uso de su tiempo.',
        'Sin temeridad decimos que las llaves de la Iglesia, donadas por el mérito de Cristo, son ese tesoro.',
        'Claro está que para la remisión de las penas y de los casos reservados basta el solo poder del Papa.',
        'El verdadero tesoro de la Iglesia es el santísimo Evangelio de la gloria y de la gracia de Dios.',
        'Pero este tesoro es con razón odiadísimo, porque hace que los primeros sean los últimos.',
        'En cambio, el tesoro de las indulgencias es con razón gratísimo, porque hace que los últimos sean los primeros.',
        'Por tanto, los tesoros del Evangelio son redes con que antaño se pescaba a los hombres de riquezas.',
        'Los tesoros de las indulgencias son redes con que ahora se pescan las riquezas de los hombres.',
        'Las indulgencias que los predicadores pregonan como gracias grandísimas, se entienden ciertamente grandes en cuanto procuran ganancia.',
        'Pero en verdad son mínimas comparadas con la gracia de Dios y la piedad de la cruz.',
        'Los obispos y curas están obligados a admitir con toda reverencia a los comisarios de las indulgencias apostólicas.',
        'Pero más obligados están a mirar con todos sus ojos y oídos, no sea que en lugar de la comisión del Papa prediquen sus propios sueños.',
        'Quien habla contra la verdad de las indulgencias apostólicas, sea anatema y maldito.',
        'Pero quien se opone a la lujuria y licencia de las palabras del predicador de indulgencias, sea bendito.',
        'Así como el Papa con razón fulmina a quienes maquinan cualquier fraude contra el negocio de las indulgencias,',
        'mucho más quiere fulminar a quienes, so pretexto de las indulgencias, maquinan fraude contra la santa caridad y la verdad.',
        'Pensar que las indulgencias papales son tan poderosas que absolverían a un hombre aunque hubiese violado, por imposible, a la Madre de Dios, es locura.',
        'Decimos, por el contrario, que las indulgencias papales no pueden quitar el menor de los pecados veniales en cuanto a la culpa.',
        'Decir que ni san Pedro, si ahora fuera Papa, podría conceder mayores gracias, es blasfemia contra san Pedro y contra el Papa.',
        'Decimos, por el contrario, que este y cualquier Papa tiene mayores gracias, esto es, el Evangelio, las virtudes, los dones de sanidad, etc., como está en 1 Corintios 12.',
        'Decir que la cruz erigida solemnemente con las armas del Papa vale tanto como la cruz de Cristo, es blasfemia.',
        'Los obispos, curas y teólogos que permiten que tales sermones corran entre el pueblo, tendrán que dar cuenta de ello.',
        'Esta licenciosa predicación de indulgencias hace que ni aun a los hombres doctos les sea fácil defender la reverencia del Papa contra las calumnias o las agudas preguntas de los legos.',
        'Como esta: ¿Por qué el Papa no vacía el purgatorio por amor santísimo y por la suma necesidad de las almas —causa justísima—, si redime infinitas almas por dinero pestilente para edificar una basílica —causa levísima?',
        'Igualmente: ¿Por qué continúan las exequias y aniversarios de los difuntos, y no devuelve o permite retirar lo dado por ellos, siendo ya injusto orar por los redimidos?',
        'Igualmente: ¿Qué nueva piedad de Dios y del Papa es esta, que por dinero permiten al impío y enemigo rescatar un alma piadosa y amada de Dios, y no la rescatan por amor a esa misma alma piadosa, a causa de su necesidad?',
        'Igualmente: ¿Por qué los cánones penitenciales, ya de hecho abrogados y muertos por desuso, se pagan aún con dinero mediante la concesión de indulgencias, como si estuvieran vivísimos?',
        'Igualmente: ¿Por qué el Papa, cuya riqueza es hoy más opulenta que la de los más ricos Cresos, no edifica al menos esta basílica de san Pedro con su propio dinero, antes que con el de los pobres fieles?',
        'Igualmente: ¿Qué remite o comunica el Papa a quienes por perfecta contrición tienen derecho a plena remisión y comunicación?',
        'Igualmente: ¿Qué mayor bien recibiría la Iglesia si el Papa, en vez de una sola vez como ahora, cien veces al día concediera estas remisiones a cualquier fiel?',
        'Si el Papa busca con las indulgencias la salud de las almas más que el dinero, ¿por qué suspende las cartas e indulgencias antes concedidas, siendo igualmente eficaces?',
        'Reprimir estos escrupulosísimos argumentos de los legos con la sola fuerza, y no resolverlos exponiendo la razón, es exponer la Iglesia y al Papa a la irrisión de los enemigos y hacer infelices a los cristianos.',
        'Si, pues, las indulgencias se predicaran según la mente y el sentir del Papa, todos estos argumentos se resolverían con facilidad; más aún, no existirían.',
        'Váyanse, pues, todos aquellos profetas que dicen al pueblo de Cristo «Paz, paz», y no hay paz.',
        'Bien les vaya a todos aquellos profetas que dicen al pueblo de Cristo «Cruz, cruz», y no hay cruz.',
        'Hay que exhortar a los cristianos a que se esfuercen por seguir a Cristo, su cabeza, a través de penas, muertes e infiernos.',
        'Y así confíen entrar en el cielo más por muchas tribulaciones que por la seguridad de la paz.'
      ]
    }
  }

};
